name: GitHub Actions Demo for Git Masterclass
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on:
  push:
  pull_request:
    branches:
      - "feat-*"

jobs:
  bash-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The tested branch is ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo 'Running `test-<YOUR-NAME>.sh` tests…'
      - name: Run tests
        run: bash ${{ github.workspace }}/test-*.sh
